package in.co.decimal.learnspringboot.courses.bean;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity // this entity used for map this Course table to our database:
//@Entity(name = "Course1") // now the table would we Course1 in our database:
public class Course {
	@Id // here id is our primary key
	@GeneratedValue(strategy = GenerationType.AUTO) // this would be autogenerated the id
	private long id;

	//@Column(name = "course_name") // now name is replace by course_name:
	private String name;

	//@Column(name = "course_author") // now autho is replace by course_author:
	private String author;
}
